#!/usr/bin/bash

# Colorful prompt
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Include Git 
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\n\[\e[31m\][\u@\h]\[\e[0m\] \[\e[36m\]\w\[\e[01;37m\]\$(parse_git_branch)\[\e[0m\]\n\$ "
#export PS1="\n\[\e[31m\][\u@\h]\[\e[0m\] \[\e[36m\]\w\[\e[0m\]\n\$ "
